In [4]:
import pandas as pd
import pickle
filename = open('./data/total.pickle','rb')
df = pickle.load(filename)

In [5]:
df

,company,country,description,location,review,salary,star,title
10,UMeKang,Singapore,"Use all available data, undertaking data disco...",Singapore,None,"$9,000 - $11,000 a month",None,Data Scientist
3,Cresco Data Pte Ltd,Singapore,Data Scientist Duties:. We are looking for a D...,Tanjong Pagar,None,"$3,500 - $4,500 a month",None,Data Scientist
8,iKas International (Asia) Pte Ltd,Singapore,"Using data modeling, linear regression, statis...",Singapore,None,"$7,000 - $9,000 a month",None,Data Scientist
6,Vault Dragon,Singapore,Assist the Data Scientist in deploying Machine...,Singapore,None,"$4,000 - $6,000 a month",None,Data Engineer
5,TSA Solutions,Singapore,Data Scientist - Summary*. Bachelor in degree ...,Pasir Panjang,None,"$4,200 a month",None,Data Scientist
4,EkkBaz.com,Singapore,We are looking for a Data Scientist that will ...,Ang Mo Kio,None,"$1,000 - $2,000 a month",None,Data Scientist Intern
10,6Estates Pte Ltd,Singapore,Assist to organise unstructured data on websit...,Singapore,None,"$1,000 a month",None,Data Crawling Engineer Intern
5,Transforma,Singapore,Develop and implement algorithms for 3D recons...,Singapore,None,"$3,500 - $5,500 a month",None,Robot Software Engineer - Image Processing
10,Shentilium Technologies,Singapore,"Perform ETL, data cleaning and data crowdsourc...",Singapore,None,"$1,000 a month",None,Data Visualization and Wrangling Intern
10,TSA Solutions,Singapore,Knowledge of SQL for retrieving data. Support ...,Singapore,None,"$3,000 - $4,300 a month",None,Data Analyst
4,BGC Group Pte Ltd,Singapore,Assist in basic data entry and other administr...,Singapore,3,"$1,300 - $1,600 a month",40.8,Data Analyst (1.6/mth) - XY
4,Beacon Consulting,Singapore,Data cleaning (e.g. Update fieldwork on data i...,Singapore,None,"$3,000 - $6,000 a month",None,Research Analyst (Data Analytics)
9,Raintree Partnership,Singapore,Financial Markets Analyst. Analyze data points...,Central Business District,None,"$6,000 - $7,500 a month",None,Financial Markets Analyst
6,Beacon Consulting,Singapore,Data cleaning (e.g. Update fieldwork on data i...,Singapore,None,"$3,000 - $6,000 a month",None,Research Analyst (Full-time)
9,Collabera,Singapore,Installing/de-installing/relocating all Data C...,Singapore,479,"$4,300 a month",42.6,Data Center Infrastructure Analyst
7,TSA Solutions,Singapore,Knowledge of SQL for retrieving data. Support ...,Pasir Panjang,None,"$3,000 - $4,000 a month",None,Business Analyst
4,Prime Solutions Provider Pte Ltd,Singapore,Analyse financial data by monitoring market tr...,Singapore,None,"$3,500 a month",None,Junior Financial Analyst
7,Aimia,Singapore,Find the best ways of working with the client ...,Singapore,74,"$10,000 a month",42.6,Analytics Manager
3,TSA Solutions,Singapore,Knowledge of SQL for retrieving data. Support ...,Singapore,None,"$3,000 - $4,000 a month",None,Revenue Performance Analyst
9,Thermo Fisher Scientific,Singapore,Experience using advanced analytical tools (SQ...,Singapore,1441,"$3,800 - $4,200 a month",42.6,Transport Analyst - Costing and Logistic(SQL)
5,Acetech Manpower Consultancy Pte Ltd,Singapore,Conducting data audits. Maintaining accurate i...,Kallang,None,"$3,000 a month",None,Asset Management Analyst
10,JMC Group Employment Agency,Singapore,Installing/de-installing/relocating all Data C...,Singapore,None,"$3,500 - $4,200 a month",None,Data Center Operator
12,inVentiv Health Clinical,Singapore,"Collect, track, and verify the accuracy of dat...",Singapore,74,"$4,500 - $5,000 a month",43.8,Project Financial Analyst
5,Drake International,Singapore,Conversion of Data Migration. Define and prepa...,Singapore,164,"$3,500 - $4,500 a month",42.6,UAT Tester / Project Assistant – Supply Chain ...
7,TSA Solutions,Singapore,Knowledge of SQL for retrieving data. Support ...,Pasir Panjang,None,"$3,000 - $4,300 a month",None,Revenue Analyst
6,Aeon Search Consulting,Singapore,"Lead in designing, specifying and selecting in...",Singapore,None,"$10,000 - $12,000 a month",None,Solution Architect - Telehealth /Up to $12K
4,TSA Solutions,Singapore,Data extrapolation (needs to be good in excel ...,Tanjong Pagar,None,"$1,400 - $1,600 a month",None,Temp Analyst (Project Based)
8,Winova Pte Ltd,Singapore,Therefore the need to support basic ad-hoc pro...,Singapore,None,"$3,000 - $3,200 a month",None,Sales & Application Engineer
3,Upskills Pte. Ltd,Singapore,Proven data mapping abilities and system conne...,Singapore,None,"$3,000 - $6,000 a month",None,MXML Interface Developer
6,Par Excellence Search Consulting Inc.,Singapore,"We know this is a client manager, data guru, a...",Singapore,None,"$3,500 - $4,000 a month",None,Customer Success Manager
...,...,...,...,...,...,...,...,...
6,Just Digital People,Australia,Strong data interpretation skills. Let's keep ...,Brisbane QLD,None,"$100,000 a year",None,Commercial Analyst | Identify Market Opportuni...
3,the turner group,Australia,Experience dealing in applications as an assis...,Brisbane QLD,2,"$60,000 - $65,000 a year",51.0,Credit Analyst - Equipment & Commercial Finance
2,Just Digital People,Australia,As a Business Analyst you're likely obsessed d...,Brisbane QLD,None,"$100,000 a year",None,UX/BA | eComm Savvy - you're discovering and c...
4,Classic Executive Recruiting,Australia,Development of the CRM system to ensure accura...,Brisbane QLD,None,"$75,000 - $85,000 a year",None,Asset Analyst – Mobile Equipment
8,Digital Native,Australia,It is essential that the candidate for this ro...,Brisbane QLD,None,"$90,000 - $100,000 a year",None,Commercial Analyst - Digital \ eCommerce
2,Just Digital People,Australia,As a Business Analyst you're likely obsessed d...,Brisbane QLD,None,"$100,000 a year",None,UX/BA | eComm Savvy - you're discovering and c...
4,Classic Executive Recruiting,Australia,Development of the CRM system to ensure accura...,Brisbane QLD,None,"$75,000 - $85,000 a year",None,Asset Analyst – Mobile Equipment
8,Digital Native,Australia,It is essential that the candidate for this ro...,Brisbane QLD,None,"$90,000 - $100,000 a year",None,Commercial Analyst - Digital \ eCommerce
4,University Of Western Australia,Australia,Experience with statistical software packages ...,Perth Central Business District WA,18,"$67,352 - $91,397 a year",52.2,"Research Associate, Statistician"
6,CSIRO,Australia,Postdoctoral Fellows are appointed for up to t...,Perth WA,26,"$91,000 a year",52.8,CSIRO Postdoctoral Fellowship in Analytical an...
1,CSIRO,Australia,Postdoctoral Fellows are appointed for up to t...,Perth WA,26,"$91,000 a year",52.8,CSIRO Postdoctoral Fellowship in Geomicrobiology
2,CSIRO,Australia,Successful candidates will develop innovative ...,Perth WA,26,"$80,000 - $91,000 a year",52.8,Deep Earth Imaging Postdoctoral Fellow
7,CSIRO,Australia,Work with leading scientists in world-class fa...,Perth WA,26,"$91,000 a year",52.8,CSIRO Postdoctoral Fellowship in ocean-atmosph...
1,CSIRO,Australia,Postdoctoral Fellows are appointed for up to t...,Perth WA,26,"$91,000 a year",52.8,CSIRO Postdoctoral Fellowship in Geomicrobiology
2,CSIRO,Australia,Successful candidates will develop innovative ...,Perth WA,26,"$80,000 - $91,000 a year",52.8,Deep Earth Imaging Postdoctoral Fellow
7,CSIRO,Australia,Work with leading scientists in world-class fa...,Perth WA,26,"$91,000 a year",52.8,CSIRO Postdoctoral Fellowship in ocean-atmosph...
9,City of Fremantle,Australia,Data collection program. The GIS Analyst is. A...,Fremantle WA,None,"$98,111 - $102,523 a year",None,GIS Analyst
0,Michael Page,Australia,You will extract the data available to you to ...,Perth WA,157,$35 - $45 an hour,42.0,Improvement Analyst
3,Michael Page,Australia,Data Analysis & Development Industry:. They ar...,Perth Central Business District WA,157,"$80,000 - $95,000 a year",42.0,Test Analyst
7,Michael Page,Australia,Newly created role Stable working environment;...,Perth WA,157,"$70,000 - $90,000 a year",42.0,Software Analyst
8,Michael Page,Australia,Analysis of a variety of data. Operating as a ...,Perth Central Business District WA,157,"$85,000 - $95,000 a year",42.0,Financial Analyst
0,Michael Page,Australia,Liaising/meeting with the Project Managers to ...,Perth Central Business District WA,157,"$85,000 - $90,000 a year",42.0,Project Analyst 12 month FTC
2,Hudson,Australia,"Financial data analysis, reporting, benchmarki...",Perth WA,156,"$45,000 - $55,000 a year",42.6,Asset and Mobile Asset Analyst
3,Hays,Australia,Experience in Virtual Data Rooms is essential....,Perth WA,466,"$85,000 a year",42.6,Business Analyst - Experience with VDR essential
2,2XM Finance,Australia,Permanent position for an experienced Business...,Perth WA,3,"$85,000 - $90,000 a year",60.0,Business Development Analyst | Perth CBD | $90K
6,2XM Finance,Australia,"Data cleansing, cleaning up the historical wor...",Perth WA,3,$40 - $45 an hour,60.0,Senior Accountant | Perth | $45p/h
2,Deimos Technology Pty Ltd,Australia,"Non-ICT Business Analysts (for example, Manage...",Mandurah WA,None,"$60,000 - $68,000 a year",None,ICT Business Analyst
5,Deimos Technology Pty Ltd,Australia,Confirms project requirements by reviewing pro...,Mandurah WA,None,"$60,000 - $70,000 a year",None,Developer Programmer
2,Deimos Technology Pty Ltd,Australia,"Non-ICT Business Analysts (for example, Manage...",Mandurah WA,None,"$60,000 - $68,000 a year",None,ICT Business Analyst
5,Deimos Technology Pty Ltd,Australia,Confirms project requirements by reviewing pro...,Mandurah WA,None,"$60,000 - $70,000 a year",None,Developer Programmer